Revert change of fields var in method signature
Otherwise odoo.api will call read_group using 'fields' in kwargs
and throw:
TypeError: read_group() got an unexpected keyword argument 'fields'